#!/usr/bin/ruby

local_branches = `git branch -l --sort=-committerdate --format='%(refname:short)'`.lines
to_delete = []
old_enough = 0
local_branches.each do |branch|
  old_enough += 1 if branch =~ /(release|master)/
  to_delete << branch if old_enough >= 3 
end
to_delete.reject { |branch| branch =~ /(release|master)/ }
         .each { |branch| puts "removing local branch: #{branch}" }
         .each { |branch| `git branch -D #{branch}` }
local_branches = `git branch -l --sort=-committerdate --format='%(refname:short)'`
puts "remaining branches:\n#{local_branches}"
