#!/usr/bin/ruby

local_branches = `git branch -l --sort=-committerdate --format='%(refname:short)'`.lines
to_delete = []
old_enough = false
local_branches.each do |branch|
  old_enough = true if branch =~ /release/
  to_delete << branch if old_enough
end
to_delete.reject { |branch| branch =~ /release/ }
         .each { |branch| puts "removing local branch: #{branch}" }
         .each { |branch| `git branch -D #{branch}` }
local_branches = `git branch -l --sort=-committerdate --format='%(refname:short)'`
puts "remaining branches:\n#{local_branches}"
